name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR Login
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 447633182123.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Image
        run: docker build -t mani-app .

      - name: Tag Image
        run: docker tag mani-app:latest 447633182123.dkr.ecr.us-east-1.amazonaws.com/mani-devops-app:latest

      - name: Push Image
        run: docker push 447633182123.dkr.ecr.us-east-1.amazonaws.com/mani-devops-app:latest